spring:
  data:
    mongodb:
      username: naveen
      password: naveen
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin
  profiles:
    active: dev
server:
  port: 8088



