package com.gameof3.gameof3artifact.Orchestrate;

import com.gameof3.gameof3artifact.ChatRoom.ChatRoomService;
import com.gameof3.gameof3artifact.Game.Game;
import com.gameof3.gameof3artifact.Game.GameService;
import com.gameof3.gameof3artifact.Game.PlayerMode;
import com.gameof3.gameof3artifact.chat.PlayerMessageService;
import com.gameof3.gameof3artifact.chat.PlayerMessage;
import com.gameof3.gameof3artifact.clientmessage.ClientMessageService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
/**
 * Orchestrate service to talk to different services and coordinate between them
 */
public class OrchestrateService {

    private final PlayerMessageService playerMessageService;
    private final GameService gameService;
    private final ChatRoomService chatRoomService;
    private final ClientMessageService clientMessageService;

    /**
     * Method to process message between 2 players
     * @param playerMessage
     */
    public void processPlayerMessage(PlayerMessage playerMessage) {
        int playerNumber = playerMessageService.processMessage(playerMessage);
        var chatId = chatRoomService.getOrCreateChatId(playerMessage.getSenderId(), playerMessage.getRecipientId());
        playerMessage.setChatId(chatId);
        Game game = gameService.findActiveGame(chatId);

        // Check if no active game
        if(game==null){
            System.out.println("Did not find any active game");
            // Rule check: Fist number can only be -1
            if(playerNumber==-1){
                gameService.startNewGame(playerMessage);
                // Send: -1
                clientMessageService.sendRegularMessage(playerMessage);
                // Send: Game has started by playerMessage.getSenderId()
                clientMessageService.sendGameStartedMessage(playerMessage);

                // Send: Random number generated by server
                clientMessageService.sendRandomNumberMessage(playerMessage);

            }else{
                clientMessageService.sendInvalidNumberMessage(playerMessage);
            }
        }
        // If active game is already present
        else{
            boolean validSender = playerMessageService.isValidSender(playerMessage);
            // Rule number 1 check : Who can send the message
            if(validSender==false){
                // Reject the message of this invalid sender and ask to wait for next participants turn
                clientMessageService.sendInvalidSenderMessage(playerMessage);
            }else{
                int validNumber = playerMessageService.getNextMoveNum(playerMessage);

                // Rule number 2 check: What should be the next number
                if(playerNumber==validNumber){
                    if(playerNumber==1){

                        // Send : 1
                        clientMessageService.sendLastMessage(playerMessage);
                        // Send : Game won by playerMessage.getSenderId()
                        clientMessageService.sendGameResultMessage(playerMessage);
                        // Mark the game over
                        gameService.completeGame(game);
                    }
                    else {
                            clientMessageService.sendRegularMessage(playerMessage);
                    }
                }else{
                    clientMessageService.sendRegularInvalidMessage(playerMessage, playerNumber);
                }
            }
        }
    }
}
